### ISSUE TITLE
Problems with solving environment 

### ISSUE THREAD

**Issue by Tomkourou** [pypsa-meets-africa/pypsa-africa-hackathon#6]
When I tried to install the environment using conda env create -f envs/environment.yaml it wasn't able to solve, just ran in an endless loop. 

I managed to install all the packages with mamba one by one except: 
1. snakemake-minimal. For that one I used conda install -c bioconda snakemake-minimal 
2. Couldnt install shapely=1.8a1 but I did install shapely using conda install -c conda-forge shapely 
3. ipython was installed using conda.

I am using a windows machine and using the terminal from VS code

**Comment by pz-max** [comment]
Looking at the CI run, the environment seems to [solve for windows ](https://github.com/pypsa-meets-africa/pypsa-africa/runs/5176188947?check_suite_focus=true), however, there is some error at the workflow execution that the ipopt is not properly that crashes the execution.

A couple of colleagues are running pypsa-africa on windows. So there seems to be a solution. Please let us know if you solve your issues and how you did it

**Comment by Tomkourou** [comment]
I just installed the packages individually and it worked fine for me.
